robot:
  amr:
    velodyne:
      vlp16_filter:
        ros__parameters:
          filter1:
            name: angle
            type: laser_filters/LaserScanAngularBoundsFilter
            params:
              lower_angle: -3.14
              upper_angle: 1.57
